Repository ellamaolson/Degree-Planning-Assistant, pull requests merged in 2019-11, with the labels that each got.

#4 001-Landing (Frontend)
  .gitignore
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/landing/landing.component.css
  client/src/app/landing/landing.component.html
  client/src/app/landing/landing.component.spec.ts
  client/src/app/landing/landing.component.ts
  client/src/assets/placeholderImg-books.jpg
  client/src/assets/placeholderImg-desk.jpg
  client/src/assets/placeholderImg-write.jpg
  client/src/styles.css
Labels: sprint-1

#6 Update client readme
  client/README.md
Labels: documentation, sprint-1

#5 006-Login/Register/Passport-jwt (Backend)
  README.md
  server/.gitignore
  server/App.js
  server/README.md
  server/config/global.js
  server/controller/constant.js
  server/controller/user.controller.js
  server/database/constant.js
  server/database/drop.sql
  server/database/init.sql
  server/database/mysql.js
  server/package.json
  server/passport.js
  server/store/config.js
  server/store/passport.js
  server/store/utils.js
Labels: enhancement, sprint-1
